[package]
name = "fastxgz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.27"

[dependencies.xxhash-rust]
version = "0.8.6"
features = ["xxh3"]